# Generated by Django 3.2.16 on 2022-11-15 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_twined", "0013_alter_serviceusageevent_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooFightingTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "number_of_questions",
                    models.IntegerField(
                        help_text="The number of questions that will get created and sent to the foo-fighting service."
                    ),
                ),
                (
                    "max_duration",
                    models.IntegerField(
                        help_text="The duration of calculation in seconds that each service will run for."
                    ),
                ),
                (
                    "randomise_duration",
                    models.BooleanField(
                        default=False,
                        help_text="Randomise durations of calculation if True. If False, all calculations will run for max_durations seconds.",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FooFightingQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_twined.question",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "calculation_status",
                    models.IntegerField(
                        choices=[
                            (-100, "No status"),
                            (-3, "Failed (invalid inputs)"),
                            (-2, "Failed (timeout)"),
                            (-1, "Failed (error)"),
                            (0, "In progress"),
                            (1, "Complete"),
                        ],
                        default=-100,
                    ),
                ),
                (
                    "foo_fighting_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foo_fighting_questions",
                        to="example.foofightingtest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
            bases=("django_twined.question",),
        ),
    ]
